export const KEY_COMMANDS = {
  full: 'F',
  grid: 'G',
  admin: 'A',
  prev: ['J', 'ARROWLEFT'],
  next: ['L', 'ARROWRIGHT'],
  edit: 'E',
  favorite: 'P',
  unfavorite: 'X',
  toggleHide: 'H',
  download: 'D',
  sync: 'S',
  search: ['⌘', 'K'],
  delete: ['⌘', 'BACKSPACE'],
} as const;
