/* eslint-disable max-len */

export type AiAutoGeneratedField =
  'title' |
  'caption' |
  'tags' |
  'semantic'

export const ALL_AI_AUTO_GENERATED_FIELDS: AiAutoGeneratedField[] = [
  'title',
  'caption',
  'tags',
  'semantic',
];

export const parseAiAutoGeneratedFieldsText = (
  text = 'all',
): AiAutoGeneratedField[] => {
  const textFormatted = text.trim().toLocaleLowerCase();
  if (textFormatted === 'none') {
    return [];
  } else if (textFormatted === 'all') {
    return ALL_AI_AUTO_GENERATED_FIELDS;
  } else {
    const fields = textFormatted
      .toLocaleLowerCase()
      .split(',')
      .map(field => field.trim())
      .filter(field => ALL_AI_AUTO_GENERATED_FIELDS
        .includes(field as AiAutoGeneratedField));
    return fields as AiAutoGeneratedField[];
  }
};

export type AiImageQuery =
  'title' |
  'caption' |
  'title-and-caption' |
  'tags' |
  'description-small' |
  'description' |
  'description-large' |
  'description-semantic';

export const PHOTO_GENRES = ['portrait photography', 'landscape photography', 'animal photography', 'street photography', 'event photography'] as const;
export type PhotoGenre = typeof PHOTO_GENRES[number];

// Fixed mapping of genres to their Chinese translations
export const GENRE_TRANSLATIONS: Record<PhotoGenre, string> = {
  'portrait photography': '人像摄影',
  'landscape photography': '风光摄影',
  'animal photography': '动物摄影',
  'street photography': '街拍摄影',
  'event photography': '活动摄影',
};

export const AI_IMAGE_QUERIES: Record<AiImageQuery, string> = {
  'title': 'You are a creative bilingual poet and photography curator. Create a unique and imaginative title for this image in both English and Chinese. Be bold and experimental - consider metaphors, emotions, abstract concepts, or sensory experiences. Avoid generic descriptions. Each time, try a completely different style or perspective. Format: "English Title | 中文标题". Keep each title within 5-6 words. The title should capture the essence, mood, or story of the image in an unexpected way. Do not describe or identify any people.',
  'caption': 'As a photography curator, craft an artistic bilingual caption that captures the visual essence and photographic qualities of this scene. Focus on light, composition, mood, colors, or textures. Be creative with your language but stay focused on the photographic elements. Format: "English Caption | 中文说明". Keep each caption within 8 words but make them impactful. Do not describe or identify any people.',
  'title-and-caption': 'You are a creative bilingual poet and photography curator. First, create a unique and imaginative title in both languages - be bold and experimental, using metaphors, emotions, or abstract concepts. Avoid generic descriptions. Then write a complementary poetic caption that expands on the title\'s theme. Format: Title: "English Title | 中文标题" Caption: "English Caption | 中文说明". Keep titles within 5-6 words and captions within 8 words. Do not describe or identify any people.',
  'tags': `First, identify which ONE genre best describes this image from ONLY these options: portrait photography (人像摄影), landscape photography (风光摄影), animal photography (动物摄影), street photography (街拍摄影), event photography (活动摄影). Then generate exactly 10 tags in this strict format: first 5 tags in English (starting with the genre), followed by 5 tags in Chinese (starting with the genre's exact translation as provided). Focus on visual elements, mood, lighting, environment, and atmosphere. Do not describe or identify any people. Format your response as a simple comma-separated list. Example for a landscape photo: "landscape photography, mountains, sunlight, morning, misty, 风光摄影, 山脉, 阳光, 早晨, 薄雾"`,
  'description-small': 'Write a concise yet vivid description focusing on the key visual elements, mood, and atmosphere. Start directly with active, descriptive language. Focus on what makes this image unique or striking. Avoid generic phrases like "This image shows" or "This is a picture of".',
  'description': 'Write a balanced description that covers composition, lighting, mood, and subject matter. Include notable technical aspects like depth of field, color palette, or framing. Describe the overall visual impact and any interesting details that contribute to the image\'s story.',
  'description-large': 'Provide a comprehensive analysis of the image covering: 1) Technical aspects (composition, lighting, color, focus), 2) Subject matter and visual elements, 3) Mood and atmosphere, 4) Artistic choices and their impact, 5) Notable details and their contribution to the overall image. Use specific photography terminology where relevant.',
  'description-semantic': 'List exactly 5 key elements or subjects in this image as a comma-separated list. Focus on concrete, visually distinct elements that define the scene. List them in order of visual prominence. Be specific but concise, using precise nouns without additional description.',
};

export const parseTitleAndCaption = (text: string) => {
  const matches = text.includes('Title')
    ? text.match(/^[`'"]*Title: ["']*(.*?)["']*[ ]*Caption: ["']*(.*?)\.*["']*[`'"]*$/)
    : text.match(/^(.*?): (.*?)$/);

  return {
    title: matches?.[1]?.trim() ?? '',
    caption: matches?.[2]?.trim() ?? '',
  };
};

export const parseBilingualTags = (text: string): string[] => {
  return text.split(',').map(t => t.trim());
};

export const cleanUpAiTextResponse = (text: string) =>
  text
    .replaceAll('\n', ' ')
    .replaceAll('"', '')
    .replace(/\.$/, '');
